#!/usr/bin/env node
const path = require('path');
const fs = require('fs').promises;
const {
  runSchema,
  runJsonFile,
  runCodePlan,
  syncJsonModules,
  watchJsonModules
} = require('./index');

function printJsonModuleSummary(result) {
  const summary = {
    folders: result.discoveredDirs.length,
    filesWritten: result.results.reduce((total, entry) => total + entry.written.length, 0),
    filesSkipped: result.results.reduce((total, entry) => total + entry.skipped.length, 0)
  };

  console.log(`JSON module sync complete. folders=${summary.folders} written=${summary.filesWritten} skipped=${summary.filesSkipped}`);
  if (result.discoveredDirs.length > 0) {
    console.log('Detected JSON module folders:');
    for (const folder of result.discoveredDirs) {
      console.log(`  - ${folder}`);
    }
  }

  const warnings = result.results.flatMap(entry => entry.warnings);
  if (warnings.length > 0) {
    console.log('Warnings:');
    for (const warning of warnings) {
      console.log(`  - ${warning}`);
    }
  }
}

async function showUsage() {
  console.log('json-forge - JSON-driven filesystem creator/editor');
  console.log('Usage:');
  console.log('  json-forge run <spec.json> [baseDir]');
  console.log('  json-forge code <plan.json> [baseDir]');
  console.log('  json-forge modules [baseDir]');
  console.log('  json-forge watch [baseDir]');
  console.log('  json-forge demo [baseDir]');
  console.log('  json-forge help');
  process.exit(0);
}

async function main() {
  const argv = process.argv.slice(2);
  if (argv.length === 0 || argv[0] === 'help') {
    return showUsage();
  }

  const cmd = argv[0].toLowerCase();
  const baseDir = path.resolve(process.cwd(), argv[2] || '.');

  if (cmd === 'run') {
    const specPath = argv[1];
    if (!specPath) return showUsage();
    const absSpecPath = path.resolve(process.cwd(), specPath);
    const result = await runJsonFile(absSpecPath, baseDir);
    console.log('Done:', result);
    return;
  }

  if (cmd === 'code') {
    const planPath = argv[1];
    if (!planPath) return showUsage();
    const absPlanPath = path.resolve(process.cwd(), planPath);
    const planText = await fs.readFile(absPlanPath, 'utf8');
    const plan = JSON.parse(planText);
    const result = await runCodePlan(plan, baseDir);
    console.log('Code plan result:', result);
    return;
  }

  if (cmd === 'modules') {
    const workDir = path.resolve(process.cwd(), argv[1] || '.');
    const result = await syncJsonModules(workDir);
    printJsonModuleSummary(result);
    return;
  }

  if (cmd === 'watch') {
    const workDir = path.resolve(process.cwd(), argv[1] || '.');
    const watcher = await watchJsonModules(workDir, {
      onSync(result) {
        printJsonModuleSummary(result);
      },
      onError(error) {
        console.error('Watch sync error:', error.message || error);
      }
    });

    console.log(`Watching JSON module folders under ${workDir}. Press Ctrl+C to stop.`);
    process.on('SIGINT', () => {
      watcher.close();
      process.exit(0);
    });
    return;
  }

  if (cmd === 'demo') {
    const workDir = path.resolve(process.cwd(), argv[1] || '.');
    const demoSpec = {
      operations: [
        { op: 'createFolder', path: 'Code' },
        {
          op: 'createFile',
          path: 'Code/hello-world.txt',
          content: 'Generated by json-forge demo.'
        },
        {
          Folder: 'Code',
          File: 'demo-script',
          file_type: 'js',
          content: "console.log('Hello from json-forge!');"
        },
        {
          op: 'edit',
          path: 'Code/hello-world.txt',
          append: '\nAppended line.'
        }
      ]
    };

    const result = await runSchema(demoSpec, workDir);
    console.log('Demo created under', workDir);
    console.log(result);
    return;
  }

  console.error('Unknown command', cmd);
  showUsage();
}

main().catch(err => {
  console.error('Error:', err.message || err);
  process.exit(1);
});
